# -*- mode: ruby -*-
# vi: set ft=ruby :

image_ip = "192.168.39.151"

box = "bento/centos-6.7"

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.network "public_network", ip: image_ip, bridge: "eno1", netmask: "255.255.0.0"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    yum install -y epel-release git
    yum install -y ansible

    rm -rf ansible-isucon
    git clone https://github.com/matsuu/ansible-isucon.git
    (
      cd ansible-isucon/isucon2
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook playbook.yml -i local
    )
    rm -rf ansible-isucon
  SHELL

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "ansible/playbook.yml"
  #end
end
