# -*- mode: ruby -*-
# vi: set ft=ruby :

image_ip = "192.168.39.176"
bench_ip = "192.168.39.177"

box = "bento/debian-8.4"

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

### image
  config.vm.define "image" do |web|
    web.vm.network "public_network", ip: image_ip, bridge: "eno1", netmask: "255.255.0.0"
    config.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y libssl1.0.0 libssl-dev
      apt-get install -y git python-pip libpython2.7-dev libyaml-dev libffi-dev
      pip install ecdsa 'paramiko<2' markupsafe ansible

      rm -rf private-isu
      git clone https://github.com/catatsuy/private-isu.git
      (
        cd private-isu/provisioning
        PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i hosts --connection=local image/ansible/*.yml
      )
      rm -rf private-isu
    SHELL
  end

### bench
  config.vm.define "bench" do |bench|
    bench.vm.network "public_network", ip: bench_ip, bridge: "eno1", netmask: "255.255.0.0"
    config.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y git python-pip libpython2.7-dev libyaml-dev libffi-dev
      pip install ecdsa 'paramiko<2' markupsafe ansible

      rm -rf private-isu
      git clone https://github.com/catatsuy/private-isu.git
      (
        cd private-isu/ansible
        PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i production --connection=local setup-bench.yml
      )
      rm -rf private-isu
    SHELL
  end

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "ansible/playbook.yml"
  #end
end
