# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "bento/ubuntu-14.04"

GH_USER = ENV["GH_USER"] || "mmm888"
BRANCH = ENV["BRANCH"] || "master"

Vagrant.configure(2) do |config|
  config.vm.box = box

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "4"
    vb.memory = "4096"
  end

### image01
  config.vm.define "image01" do |web|
    web.vm.network "public_network", ip: "192.168.39.85", bridge: "eno1", netmask: "255.255.0.0"
    config.vm.provision "shell", inline: <<-SHELL
      set -e
      sed -i".bak" -E "s@http://(us\.|)(archive|security)\.ubuntu\.com/ubuntu@http://ftp.jaist.ac.jp/pub/Linux/ubuntu@g" /etc/apt/sources.list
      ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      apt-get -y update
      apt-get -y install git ansible

      rm -rf ansible-isucon
      git clone https://github.com/#{GH_USER}/ansible-isucon.git
      (
        cd ansible-isucon
        git checkout #{BRANCH}
        cd isucon4-qualifier-ubuntu
        PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook playbook.yml -i local
      )
      yes no | cp -ai /home/vagrant/ansible-isucon/isucon4-qualifier-ubuntu/benchmarker /home/isucon # copy benchmaker
      chown isucon: /home/isucon/benchmarker
      rm -rf ansible-isucon

      echo isucon:isucon | /usr/sbin/chpasswd
    SHELL
  end

### image02
  config.vm.define "image02" do |web|
    web.vm.network "public_network", ip: "192.168.39.86", bridge: "eno1", netmask: "255.255.0.0"
    config.vm.provision "shell", inline: <<-SHELL
      set -e
      sed -i".bak" -E "s@http://(us\.|)(archive|security)\.ubuntu\.com/ubuntu@http://ftp.jaist.ac.jp/pub/Linux/ubuntu@g" /etc/apt/sources.list
      ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      apt-get -y update
      apt-get -y install git ansible

      rm -rf ansible-isucon
      git clone https://github.com/#{GH_USER}/ansible-isucon.git
      (
        cd ansible-isucon
        git checkout #{BRANCH}
        cd isucon4-qualifier-ubuntu
        PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook playbook.yml -i local
      )
      yes no | cp -ai /home/vagrant/ansible-isucon/isucon4-qualifier-ubuntu/benchmarker /home/isucon # copy benchmaker
      rm -rf ansible-isucon

      echo isucon:isucon | /usr/sbin/chpasswd
    SHELL
  end

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "ansible/playbook.yml"
  #end
end
