# -*- mode: ruby -*-
# vi: set ft=ruby :

image_ip = "192.168.39.156"

box = "ubuntu/xenial64"

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.network "public_network", ip: image_ip, bridge: "eno1", netmask: "255.255.0.0"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends ansible git aptitude golang-go tzdata make
    export GOPATH=/tmp/go
    mkdir -p ${GOPATH}/src/github.com/isucon/
    cd ${GOPATH}/src/github.com/isucon
    rm -rf isucon6-qualify
    git clone https://github.com/isucon/isucon6-qualify.git
    sed -i -e 's:--disable-phar::' isucon6-qualify/provisioning/image/ansible/02_xbuild.yml
    (
      cd isucon6-qualify/bench
      go get github.com/Songmu/timeout
      go get github.com/mitchellh/go-homedir
      go get github.com/PuerkitoBio/goquery
      go get github.com/marcw/cachecontrol
      make
    )
    (
      cd isucon6-qualify/provisioning/bench
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i localhost, ansible/*.yml --connection=local
    )
    (
      cd isucon6-qualify
      make
      ln -s isupam_linux bin/isupam
    )
    (
      cd isucon6-qualify/provisioning/image/ansible
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i localhost, *.yml --connection=local -t dev
    )
    (
      cd isucon6-qualify/provisioning/image
      ./db_setup.sh
    )
    rm -rf ${GOPATH}

    usermod -G sudo -a -s /bin/bash isucon
    echo isucon:isucon | /usr/sbin/chpasswd

    echo "Provisioning Successful"
  SHELL
end
