# -*- mode: ruby -*-
# vi: set ft=ruby :

bench_ip   = "192.168.39.183"
image01_ip = "192.168.39.184"
image02_ip = "192.168.39.185"

#box = "bento/ubuntu-16.04"
box = "ubuntu/xenial64"

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

### bench
  config.vm.define "bench" do |web|
    web.vm.network "public_network", ip: bench_ip, bridge: "eno1", netmask: "255.255.0.0"
    config.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends ansible git aptitude golang-go make
      export GOPATH=/tmp/go
      mkdir -p ${GOPATH}/src/github.com/isucon/
      cd ${GOPATH}/src/github.com/isucon
      rm -rf isucon6-qualify
      git clone https://github.com/isucon/isucon6-qualify.git
      (
        cd isucon6-qualify/bench
	go get github.com/Songmu/timeout
	go get github.com/mitchellh/go-homedir
        go get github.com/PuerkitoBio/goquery
	go get github.com/marcw/cachecontrol
        make
      )
      (
        cd isucon6-qualify/provisioning/bench
        PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i localhost, ansible/*.yml --connection=local
      )
      rm -rf ${GOPATH}

      usermod -G sudo -a -s /bin/bash isucon
      echo isucon:isucon | /usr/sbin/chpasswd

      echo "Provisioning Successful for image"
    SHELL
  end

### image01
  config.vm.define "image01" do |web|
    web.vm.network "public_network", ip: image01_ip, bridge: "eno1", netmask: "255.255.0.0"
    config.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends ansible git aptitude golang-go tzdata make
      rm -rf isucon6-qualify
      git clone https://github.com/isucon/isucon6-qualify.git
      sed -i -e 's:--disable-phar::' isucon6-qualify/provisioning/image/ansible/02_xbuild.yml
      (
        cd isucon6-qualify
	make
	ln -s isupam_linux bin/isupam
      )
      (
        cd isucon6-qualify/provisioning/image/ansible
        PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i localhost, *.yml --connection=local -t dev
      )
      (
        cd isucon6-qualify/provisioning/image
	./db_setup.sh
      )
      rm -rf isucon6-qualify

      usermod -G sudo -a -s /bin/bash isucon
      echo isucon:isucon | /usr/sbin/chpasswd

      echo "Provisioning Successful for image"
    SHELL
  end

### iamge02
  config.vm.define "image02" do |web|
    web.vm.network "public_network", ip: image02_ip, bridge: "eno1", netmask: "255.255.0.0"
    config.vm.provision "shell", inline: <<-SHELL
      set -e
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends ansible git aptitude golang-go tzdata make
      rm -rf isucon6-qualify
      git clone https://github.com/isucon/isucon6-qualify.git
      sed -i -e 's:--disable-phar::' isucon6-qualify/provisioning/image/ansible/02_xbuild.yml
      (
        cd isucon6-qualify
	make
	ln -s isupam_linux bin/isupam
      )
      (
        cd isucon6-qualify/provisioning/image/ansible
        PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i localhost, *.yml --connection=local -t dev
      )
      (
        cd isucon6-qualify/provisioning/image
	./db_setup.sh
      )
      rm -rf isucon6-qualify

      usermod -G sudo -a -s /bin/bash isucon
      echo isucon:isucon | /usr/sbin/chpasswd

      echo "Provisioning Successful for image"
    SHELL
  end
end
