# -*- mode: ruby -*-
# vi: set ft=ruby :

image01_ip = "192.168.39.171"
image02_ip = "192.168.39.172"
image03_ip = "192.168.39.173"
image04_ip = "192.168.39.174"
bench_ip   = "192.168.39.175"

box = "ubuntu/xenial64"

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends ansible git aptitude tzdata make
    apt-get install -y 

    # install -y docker
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common 
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
    apt-get update
    apt-get install -y docker-ce

    # install -y docker-compose
    curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

    # create isucon user
    mkdir /home/isucon -p
    useradd -s /bin/bash -p isucon isucon
    usermod -aG sudo isucon
    echo isucon:isucon | /usr/sbin/chpasswd
   
    echo "Provisioning Successful"
  SHELL

### image01
  config.vm.define "image01" do |web|
    web.vm.network "public_network", ip: image01_ip, bridge: "eno1", netmask: "255.255.0.0"
  end

### image02
  config.vm.define "image02" do |web|
    web.vm.network "public_network", ip: image02_ip, bridge: "eno1", netmask: "255.255.0.0"
  end

### image03
  config.vm.define "image03" do |web|
    web.vm.network "public_network", ip: image03_ip, bridge: "eno1", netmask: "255.255.0.0"
  end

### image04
  config.vm.define "image04" do |web|
    web.vm.network "public_network", ip: image04_ip, bridge: "eno1", netmask: "255.255.0.0"
  end

### bench
  config.vm.define "bench" do |web|
    web.vm.network "public_network", ip: bench_ip, bridge: "eno1", netmask: "255.255.0.0"
  end
end
