# -*- mode: ruby -*-
# vi: set ft=ruby :

image_ip = "192.168.39.155"

box = "bento/ubuntu-15.04"

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.network "public_network", ip: image_ip, bridge: "eno1", netmask: "255.255.0.0"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    sed -i.bak -e "s@http://us\.archive\.ubuntu\.com/ubuntu/@mirror://mirrors.ubuntu.com/mirrors.txt@g" /etc/apt/sources.list
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y ansible git

    rm -rf ansible-isucon
    git clone https://github.com/matsuu/ansible-isucon.git
    (
      cd ansible-isucon/isucon5-qualifier
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local bench/ansible/playbook.yml
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local image/ansible/playbook.yml
    )
    rm -rf ansible-isucon

    echo isucon:isucon | /usr/sbin/chpasswd
  SHELL

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "ansible/playbook.yml"
  #end
end
